spring:
  application:
    name: douyin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/douyin?serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
server:
  port: 8080
douyin:
  path: D:\code\douyin\src\main\resources\
  ip_path: http://10.34.140.181:8080/
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
snowflake:
  data-center-id: 0 #雪花算法的机器标识号
  machine-id: 001 #雪花算法的数据中心标识号
video:
  limit: 10