spring:
  profiles:
    active: dev
---
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  redis:
    host: 192.168.56.129
    port: 6379
    password: Abin21428!!
  application:
    name: douyin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/douyin?serverTimezone=UTC
    username: root
    password: Abin21428!!
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  profiles: dev
server:
  port: 8080
douyin:
  path: E:\curriculum design\douyin\src\main\resources\
  ip_path: http://192.168.61.69:8080/
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
snowflake:
  data-center-id: 0 #雪花算法的机器标识号
  machine-id: 001 #雪花算法的数据中心标识号
video:
  limit: 10
logging:
  config: classpath:logback-spring.xml
  file:
    max-size: 10MB
    max-history: 7
    name: SpringbootLog
    path: D:\code\douyin\src\main\resources\log
  level:
    root: info
oss:
  endpoint: oss-cn-guangzhou.aliyuncs.com
  access-key-id: LTAI5t88KFZki6JU3x3ptwv7
  access-key-secret: 9wdqsQekhMvS2R5YAuHyNkdrJ9BOAv
  bucketname: douyin-1

---
spring:
  application:
    name: douyin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/douyin?serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  profiles: pro
server:
  port: 8080
douyin:
  path: D:\code\douyin\src\main\resources\
  ip_path: http://10.34.140.181:8080/
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
snowflake:
  data-center-id: 0 #雪花算法的机器标识号
  machine-id: 001 #雪花算法的数据中心标识号
video:
  limit: 10