spring:
  application:
    name: douyin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/douyin?serverTimezone=UTC
    username: root
    password: Abin21428!!
server:
  port: 8080
