spring:
  application:
    name: douyin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/douyin?serverTimezone=UTC
    username: root
    password: Abin21428!!
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  devtools:
#    restart:
#      enabled: true  #设置开启热部署
#      additional-paths: src/main/resources #重启目录
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
#  resources:
#    static-locations: classpath:/public/picture/,classpath:/public/video/
#  mvc:
#    static-path-pattern: /**
server:
  port: 8080
douyin:
  path: E:\curriculum design\douyin\src\main\resources
  ip_path: http://192.168.220.69:8080/
